# -*- coding: utf-8 -*-
"""footbalvideo analysis_CodeAlpha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8cip5_BT5KgfJfPmy1CNWx3L-9GosmT
"""

# ============================================================
# AI FOOTBALL ANALYTICS V3 - CLEAN PROFESSIONAL OVERLAY
# YOLO11 + ByteTrack + HSV Team Classification + OpenCV
#
# CLEAN DESIGN:
#   IRAN       -> IRN + jersey number
#   UZBEKISTAN -> UZB + jersey number
#   GOALKEEPER -> GK
#   REFEREE    -> REF
#
# VISUAL:
#   - Single clean circle under player
#   - No black shadow
#   - Modern ID badges
#   - Ball with short meteor / fire effect
#   - No giant zigzag trail
# ============================================================

# ============================================================
# 1. INSTALL
# ============================================================

!pip install -q ultralytics opencv-python-headless lap

# ============================================================
# 2. IMPORTS
# ============================================================

import cv2
import math
import torch
import numpy as np

from collections import deque
from google.colab import files
from ultralytics import YOLO


# ============================================================
# 3. CONFIG
# ============================================================

MODEL_NAME = "yolo11x.pt"

DEVICE = 0 if torch.cuda.is_available() else "cpu"

PERSON_CONF = 0.25
BALL_CONF = 0.10

# Ball uchun
MAX_BALL_JUMP = 180
BALL_SMOOTHING = 0.65
BALL_MAX_MISSING = 4

print("=" * 60)
print("AI FOOTBALL ANALYTICS V3")
print("Device:", DEVICE)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("=" * 60)


# ============================================================
# 4. UPLOAD VIDEO
# ============================================================

print("\n🎥 Kompyuteringizdan football video yuklang")

uploaded = files.upload()

VIDEO_PATH = list(uploaded.keys())[0]

print("VIDEO:", VIDEO_PATH)


# ============================================================
# 5. LOAD YOLO
# ============================================================

print("\n🚀 Loading YOLO...")

model = YOLO(MODEL_NAME)

print("YOLO READY!")


# ============================================================
# 6. VIDEO INFO
# ============================================================

cap = cv2.VideoCapture(VIDEO_PATH)

FPS = cap.get(cv2.CAP_PROP_FPS)

WIDTH = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
HEIGHT = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

TOTAL_FRAMES = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

cap.release()

DURATION = TOTAL_FRAMES / FPS

print("\nVIDEO INFO")
print("FPS:", FPS)
print("Resolution:", WIDTH, "x", HEIGHT)
print("Frames:", TOTAL_FRAMES)
print("Duration:", round(DURATION, 1), "seconds")


# ============================================================
# 7. OUTPUT
# ============================================================

OUTPUT_PATH = "/content/football_analytics_clean.mp4"

fourcc = cv2.VideoWriter_fourcc(*"mp4v")

out = cv2.VideoWriter(
    OUTPUT_PATH,
    fourcc,
    FPS,
    (WIDTH, HEIGHT)
)


# ============================================================
# 8. COLORS - BGR
# ============================================================

COLORS = {

    "IRAN": (245, 245, 245),

    "UZBEKISTAN": (255, 80, 0),

    "GOALKEEPER": (120, 255, 120),

    "REFEREE": (40, 40, 255),

    "BALL": (0, 220, 255),

    "UNKNOWN": (0, 220, 255),

    "DARK": (18, 18, 18),

    "WHITE": (255, 255, 255)
}


# ============================================================
# 9. PLAYER CLASS MEMORY
# ============================================================

PLAYER_HISTORY = {}

PLAYER_STABLE_CLASS = {}

# Track ID -> compact display number
PLAYER_DISPLAY_NUMBER = {}

NEXT_PLAYER_NUMBER = 1


# ============================================================
# 10. JERSEY REGION
# ============================================================

def get_jersey_region(frame, x1, y1, x2, y2):

    w = x2 - x1
    h = y2 - y1

    if w < 10 or h < 20:
        return None

    # Head va shortsni chiqarib tashlaymiz
    rx1 = x1 + int(w * 0.18)
    rx2 = x2 - int(w * 0.18)

    ry1 = y1 + int(h * 0.20)
    ry2 = y1 + int(h * 0.55)

    rx1 = max(0, rx1)
    ry1 = max(0, ry1)

    rx2 = min(frame.shape[1], rx2)
    ry2 = min(frame.shape[0], ry2)

    crop = frame[ry1:ry2, rx1:rx2]

    if crop.size == 0:
        return None

    return crop


# ============================================================
# 11. CLASSIFY JERSEY COLOR
# ============================================================

def classify_player(frame, x1, y1, x2, y2):

    crop = get_jersey_region(
        frame,
        x1, y1, x2, y2
    )

    if crop is None:
        return "UNKNOWN"

    hsv = cv2.cvtColor(
        crop,
        cv2.COLOR_BGR2HSV
    )

    total = crop.shape[0] * crop.shape[1]

    if total == 0:
        return "UNKNOWN"


    # --------------------------------------------------------
    # WHITE - IRAN
    # --------------------------------------------------------

    white_mask = cv2.inRange(
        hsv,
        np.array([0, 0, 160]),
        np.array([180, 75, 255])
    )


    # --------------------------------------------------------
    # BLUE - UZBEKISTAN
    # --------------------------------------------------------

    blue_mask = cv2.inRange(
        hsv,
        np.array([90, 70, 40]),
        np.array([145, 255, 255])
    )


    # --------------------------------------------------------
    # LIGHT GREEN - GOALKEEPER
    # --------------------------------------------------------

    green_mask = cv2.inRange(
        hsv,
        np.array([35, 35, 70]),
        np.array([90, 255, 255])
    )


    # --------------------------------------------------------
    # RED - REFEREE
    # --------------------------------------------------------

    red1 = cv2.inRange(
        hsv,
        np.array([0, 70, 60]),
        np.array([12, 255, 255])
    )

    red2 = cv2.inRange(
        hsv,
        np.array([165, 70, 60]),
        np.array([180, 255, 255])
    )

    red_mask = cv2.bitwise_or(
        red1,
        red2
    )


    scores = {

        "IRAN":
            cv2.countNonZero(white_mask) / total,

        "UZBEKISTAN":
            cv2.countNonZero(blue_mask) / total,

        "GOALKEEPER":
            cv2.countNonZero(green_mask) / total,

        "REFEREE":
            cv2.countNonZero(red_mask) / total
    }


    best_class = max(
        scores,
        key=scores.get
    )

    best_score = scores[best_class]

    if best_score < 0.12:
        return "UNKNOWN"

    return best_class


# ============================================================
# 12. STABILIZE PLAYER CLASS
# ============================================================

def get_stable_class(track_id, detected_class):

    if track_id == -1:
        return detected_class


    if track_id not in PLAYER_HISTORY:

        PLAYER_HISTORY[track_id] = {

            "IRAN": 0,

            "UZBEKISTAN": 0,

            "GOALKEEPER": 0,

            "REFEREE": 0,

            "UNKNOWN": 0
        }


    PLAYER_HISTORY[track_id][detected_class] += 1


    # UNKNOWN juda ko'p bo'lsa ham
    # mavjud classni buzib yubormasligi uchun

    valid_classes = [
        "IRAN",
        "UZBEKISTAN",
        "GOALKEEPER",
        "REFEREE"
    ]

    best_class = max(
        valid_classes,
        key=lambda x:
        PLAYER_HISTORY[track_id][x]
    )

    best_count = PLAYER_HISTORY[track_id][best_class]


    # Hali yetarli observation bo'lmasa
    if best_count < 2:

        stable = detected_class

    else:

        stable = best_class


    PLAYER_STABLE_CLASS[track_id] = stable

    return stable


# ============================================================
# 13. PLAYER DISPLAY NUMBER
# ============================================================

def get_display_number(track_id):

    global NEXT_PLAYER_NUMBER

    if track_id == -1:
        return 0

    if track_id not in PLAYER_DISPLAY_NUMBER:

        PLAYER_DISPLAY_NUMBER[track_id] = NEXT_PLAYER_NUMBER

        NEXT_PLAYER_NUMBER += 1

    return PLAYER_DISPLAY_NUMBER[track_id]


# ============================================================
# 14. DRAW CLEAN PLAYER CIRCLE
# ============================================================

def draw_player_circle(
    frame,
    x1,
    y1,
    x2,
    y2,
    color
):

    player_w = x2 - x1

    foot_x = int(
        (x1 + x2) / 2
    )

    foot_y = int(y2)


    # Bitta ellipse
    ellipse_w = max(
        10,
        int(player_w * 0.32)
    )

    ellipse_h = max(
        3,
        int(ellipse_w * 0.28)
    )


    cv2.ellipse(

        frame,

        (
            foot_x,
            foot_y
        ),

        (
            ellipse_w,
            ellipse_h
        ),

        0,

        0,

        360,

        color,

        2,

        cv2.LINE_AA
    )


# ============================================================
# 15. DRAW MODERN ID BADGE
# ============================================================

def draw_id_badge(
    frame,
    x1,
    y1,
    x2,
    player_class,
    display_number
):

    color = COLORS.get(
        player_class,
        COLORS["UNKNOWN"]
    )


    # -----------------------------------------
    # Compact label
    # -----------------------------------------

    if player_class == "IRAN":

        label = f"IRN {display_number}"

    elif player_class == "UZBEKISTAN":

        label = f"UZB {display_number}"

    elif player_class == "GOALKEEPER":

        label = "GK"

        if display_number > 0:
            label += f" {display_number}"

    elif player_class == "REFEREE":

        label = "REF"

    else:

        label = f"P {display_number}"


    font = cv2.FONT_HERSHEY_SIMPLEX

    font_scale = 0.55

    thickness = 2


    (text_w, text_h), baseline = cv2.getTextSize(

        label,

        font,

        font_scale,

        thickness
    )


    padding_x = 10
    padding_y = 7


    badge_w = text_w + padding_x * 2

    badge_h = text_h + padding_y * 2


    # Badge player markazida
    center_x = int(
        (x1 + x2) / 2
    )

    badge_x1 = center_x - badge_w // 2

    badge_y2 = max(
        badge_h + 5,
        y1 - 8
    )

    badge_x2 = badge_x1 + badge_w

    badge_y1 = badge_y2 - badge_h


    # -----------------------------------------
    # Dark background
    # -----------------------------------------

    cv2.rectangle(

        frame,

        (
            badge_x1,
            badge_y1
        ),

        (
            badge_x2,
            badge_y2
        ),

        (18, 18, 18),

        -1

    )


    # -----------------------------------------
    # Team color border
    # -----------------------------------------

    cv2.rectangle(

        frame,

        (
            badge_x1,
            badge_y1
        ),

        (
            badge_x2,
            badge_y2
        ),

        color,

        2

    )


    # -----------------------------------------
    # Text
    # -----------------------------------------

    cv2.putText(

        frame,

        label,

        (
            badge_x1 + padding_x,
            badge_y2 - padding_y
        ),

        font,

        font_scale,

        COLORS["WHITE"],

        thickness,

        cv2.LINE_AA
    )


# ============================================================
# 16. BALL TRACKER
# ============================================================

BALL_POSITION = None

BALL_VELOCITY = np.array(
    [0.0, 0.0]
)

BALL_MISSING = 0


def select_best_ball(
    ball_candidates,
    previous_position
):

    if len(ball_candidates) == 0:
        return None


    # Previous position yo'q bo'lsa
    # eng yuqori confidence

    if previous_position is None:

        return max(
            ball_candidates,
            key=lambda x: x[2]
        )


    best_candidate = None

    best_score = -999999


    for x, y, conf in ball_candidates:

        distance = math.dist(
            previous_position,
            (x, y)
        )


        # Confidence + previous positionga yaqinlik

        score = (
            conf * 100
            -
            distance * 0.08
        )


        if score > best_score:

            best_score = score

            best_candidate = (
                x,
                y,
                conf,
                distance
            )


    return best_candidate


# ============================================================
# 17. DRAW METEOR BALL
# ============================================================

def draw_meteor_ball(
    frame,
    position,
    velocity
):

    if position is None:
        return


    x, y = int(position[0]), int(position[1])

    vx = velocity[0]
    vy = velocity[1]

    speed = math.sqrt(
        vx * vx +
        vy * vy
    )


    # --------------------------------------------------------
    # Meteor tail faqat harakat bo'lsa
    # --------------------------------------------------------

    if speed > 2:

        # Direction normalize

        dx = vx / speed
        dy = vy / speed


        # Fire tail harakatning TESKARI tomonida

        tail_length = min(
            45,
            max(
                15,
                int(speed * 3)
            )
        )


        # Faqat 6 ta qisqa segment
        # HECH QACHON eski frame bilan ulanmaydi

        for i in range(6, 0, -1):

            ratio = i / 6.0

            tx = int(
                x - dx * tail_length * ratio
            )

            ty = int(
                y - dy * tail_length * ratio
            )


            radius = max(
                2,
                int(7 * (1 - ratio))
            )


            # Outer fire
            cv2.circle(

                frame,

                (tx, ty),

                radius + 2,

                (0, 100, 255),

                -1,

                cv2.LINE_AA
            )


            # Inner yellow
            cv2.circle(

                frame,

                (tx, ty),

                radius,

                (0, 220, 255),

                -1,

                cv2.LINE_AA
            )


    # --------------------------------------------------------
    # BALL CENTER
    # --------------------------------------------------------

    # Outer glow
    cv2.circle(

        frame,

        (x, y),

        11,

        (0, 150, 255),

        2,

        cv2.LINE_AA
    )


    # Main ball marker
    cv2.circle(

        frame,

        (x, y),

        7,

        (0, 230, 255),

        -1,

        cv2.LINE_AA
    )


    # Bright center
    cv2.circle(

        frame,

        (x, y),

        3,

        (255, 255, 255),

        -1,

        cv2.LINE_AA
    )


# ============================================================
# 18. FORMAT TIME
# ============================================================

def format_time(seconds):

    minutes = int(seconds // 60)

    seconds = int(seconds % 60)

    return f"{minutes:02d}:{seconds:02d}"


# ============================================================
# 19. DRAW TIME BADGE
# ============================================================

def draw_time_badge(
    frame,
    frame_number
):

    current_seconds = frame_number / FPS

    current_time = format_time(
        current_seconds
    )

    total_time = format_time(
        DURATION
    )


    text = (
        f"{current_time} / {total_time}"
    )


    font = cv2.FONT_HERSHEY_SIMPLEX

    scale = 0.55

    thickness = 1


    (tw, th), _ = cv2.getTextSize(

        text,

        font,

        scale,

        thickness
    )


    x1 = WIDTH - tw - 30
    y1 = HEIGHT - 42

    x2 = WIDTH - 10
    y2 = HEIGHT - 10


    cv2.rectangle(

        frame,

        (x1, y1),

        (x2, y2),

        (20, 20, 20),

        -1

    )


    cv2.putText(

        frame,

        text,

        (
            x1 + 10,
            y2 - 10
        ),

        font,

        scale,

        COLORS["WHITE"],

        thickness,

        cv2.LINE_AA
    )


# ============================================================
# 20. START ANALYSIS
# ============================================================

print("\n" + "=" * 60)
print("🚀 STARTING AI FOOTBALL ANALYTICS V3")
print("=" * 60)


frame_number = 0


results = model.track(

    source=VIDEO_PATH,

    tracker="bytetrack.yaml",

    persist=True,

    stream=True,

    verbose=False,

    device=DEVICE,

    conf=PERSON_CONF
)


# ============================================================
# 21. PROCESS VIDEO
# ============================================================

for result in results:


    frame_number += 1


    frame = result.orig_img.copy()


    # --------------------------------------------------------
    # Current frame counts
    # --------------------------------------------------------

    iran_count = 0

    uzbekistan_count = 0

    goalkeeper_count = 0

    referee_count = 0


    # --------------------------------------------------------
    # Ball candidates
    # --------------------------------------------------------

    ball_candidates = []


    # ========================================================
    # DETECTIONS
    # ========================================================

    if result.boxes is not None:


        boxes = result.boxes.xyxy.cpu().numpy()

        classes = result.boxes.cls.int().cpu().tolist()

        confidences = result.boxes.conf.cpu().numpy()


        if result.boxes.id is not None:

            track_ids = (
                result.boxes.id
                .int()
                .cpu()
                .tolist()
            )

        else:

            track_ids = [
                -1
                for _ in boxes
            ]


        # ====================================================
        # EACH DETECTION
        # ====================================================

        for box, cls_id, conf, track_id in zip(

            boxes,
            classes,
            confidences,
            track_ids
        ):


            x1, y1, x2, y2 = map(
                int,
                box
            )


            x1 = max(0, x1)
            y1 = max(0, y1)

            x2 = min(
                WIDTH - 1,
                x2
            )

            y2 = min(
                HEIGHT - 1,
                y2
            )


            # =================================================
            # PERSON
            # =================================================

            if cls_id == 0:


                player_w = x2 - x1

                player_h = y2 - y1


                if (
                    player_w < 20
                    or
                    player_h < 40
                ):

                    continue


                # ---------------------------------------------
                # Classify
                # ---------------------------------------------

                detected_class = classify_player(

                    frame,
                    x1, y1,
                    x2, y2
                )


                stable_class = get_stable_class(

                    track_id,
                    detected_class
                )


                display_number = get_display_number(
                    track_id
                )


                # ---------------------------------------------
                # Count
                # ---------------------------------------------

                if stable_class == "IRAN":

                    iran_count += 1


                elif stable_class == "UZBEKISTAN":

                    uzbekistan_count += 1


                elif stable_class == "GOALKEEPER":

                    goalkeeper_count += 1


                elif stable_class == "REFEREE":

                    referee_count += 1


                # ---------------------------------------------
                # Color
                # ---------------------------------------------

                color = COLORS.get(

                    stable_class,

                    COLORS["UNKNOWN"]
                )


                # ---------------------------------------------
                # CLEAN FOOT CIRCLE
                # ---------------------------------------------

                draw_player_circle(

                    frame,

                    x1, y1,

                    x2, y2,

                    color
                )


                # ---------------------------------------------
                # MODERN ID BADGE
                # ---------------------------------------------

                draw_id_badge(

                    frame,

                    x1, y1, x2,

                    stable_class,

                    display_number
                )


            # =================================================
            # BALL
            # =================================================

            elif cls_id == 32:


                if conf >= BALL_CONF:


                    ball_x = int(
                        (x1 + x2) / 2
                    )

                    ball_y = int(
                        (y1 + y2) / 2
                    )


                    ball_candidates.append(

                        (
                            ball_x,
                            ball_y,
                            float(conf)
                        )
                    )


    # ========================================================
    # 22. SELECT BALL
    # ========================================================

    selected = select_best_ball(

        ball_candidates,

        BALL_POSITION
    )


    if selected is not None:


        new_x = selected[0]

        new_y = selected[1]


        new_position = np.array(

            [
                float(new_x),
                float(new_y)
            ]

        )


        # ----------------------------------------------------
        # FIRST BALL
        # ----------------------------------------------------

        if BALL_POSITION is None:


            BALL_POSITION = new_position

            BALL_VELOCITY = np.array(
                [0.0, 0.0]
            )

            BALL_MISSING = 0


        else:


            distance = np.linalg.norm(

                new_position -
                BALL_POSITION

            )


            # ------------------------------------------------
            # Camera cut / false detection
            #
            # Juda katta sakrash bo'lsa
            # oldingi nuqtaga LINE CHIZILMAYDI
            # velocity reset qilinadi
            # ------------------------------------------------

            if distance > MAX_BALL_JUMP:


                BALL_POSITION = new_position

                BALL_VELOCITY = np.array(
                    [0.0, 0.0]
                )

                BALL_MISSING = 0


            else:


                # Smooth position

                previous = BALL_POSITION.copy()


                BALL_POSITION = (

                    BALL_SMOOTHING *
                    new_position

                    +

                    (1 - BALL_SMOOTHING) *
                    BALL_POSITION
                )


                # Current velocity

                new_velocity = (

                    BALL_POSITION -
                    previous
                )


                # Smooth velocity

                BALL_VELOCITY = (

                    0.7 *
                    BALL_VELOCITY

                    +

                    0.3 *
                    new_velocity
                )


                BALL_MISSING = 0


    else:


        BALL_MISSING += 1


        # Ball yo'qolsa marker ham yo'qoladi

        if BALL_MISSING > BALL_MAX_MISSING:

            BALL_POSITION = None

            BALL_VELOCITY = np.array(
                [0.0, 0.0]
            )


    # ========================================================
    # 23. DRAW BALL METEOR
    # ========================================================

    if BALL_POSITION is not None:


        draw_meteor_ball(

            frame,

            BALL_POSITION,

            BALL_VELOCITY
        )


    # ========================================================
    # 24. MINIMAL DASHBOARD
    # ========================================================

    # Background

    cv2.rectangle(

        frame,

        (10, 10),

        (330, 155),

        (12, 12, 12),

        -1
    )


    # Title

    cv2.putText(

        frame,

        "AI FOOTBALL ANALYTICS",

        (22, 38),

        cv2.FONT_HERSHEY_SIMPLEX,

        0.65,

        COLORS["WHITE"],

        2,

        cv2.LINE_AA
    )


    # Separator

    cv2.line(

        frame,

        (20, 50),

        (320, 50),

        (70, 70, 70),

        1
    )


    dashboard_data = [

        (
            "IRAN (WHITE)",
            iran_count,
            COLORS["IRAN"]
        ),

        (
            "UZBEKISTAN (BLUE)",
            uzbekistan_count,
            COLORS["UZBEKISTAN"]
        ),

        (
            "GOALKEEPER",
            goalkeeper_count,
            COLORS["GOALKEEPER"]
        ),

        (
            "REFEREE",
            referee_count,
            COLORS["REFEREE"]
        )
    ]


    y = 78


    for name, count, color in dashboard_data:


        # Color dot

        cv2.circle(

            frame,

            (28, y - 5),

            7,

            color,

            -1,

            cv2.LINE_AA
        )


        # Name

        cv2.putText(

            frame,

            name,

            (45, y),

            cv2.FONT_HERSHEY_SIMPLEX,

            0.50,

            color,

            1,

            cv2.LINE_AA
        )


        # Count

        cv2.putText(

            frame,

            str(count),

            (295, y),

            cv2.FONT_HERSHEY_SIMPLEX,

            0.55,

            COLORS["WHITE"],

            2,

            cv2.LINE_AA
        )


        y += 24


    # ========================================================
    # 25. TIME BADGE
    # ========================================================

    draw_time_badge(

        frame,

        frame_number
    )


    # ========================================================
    # 26. SAVE FRAME
    # ========================================================

    out.write(frame)


    if frame_number % 100 == 0:

        progress = (
            frame_number /
            TOTAL_FRAMES
        ) * 100


        print(

            f"Processed: "

            f"{frame_number}/{TOTAL_FRAMES} "

            f"({progress:.1f}%)"
        )


# ============================================================
# 27. FINISH
# ============================================================

out.release()


print("\n" + "=" * 60)
print("🎉 ANALYSIS FINISHED!")
print("=" * 60)

print("Output:", OUTPUT_PATH)


# ============================================================
# 28. DOWNLOAD
# ============================================================

files.download(
    OUTPUT_PATH
)